### PR TITLE
Use rayon for parallel compilation

### PR DESCRIPTION
**Pull request by nipunn1313**
Here's an attempt to add support parallel compilation (See #90).

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I find it kinda crazy that it amounts to a 2-line change when using crates like rayon to add parallelization here...

I'd like to also handle features like [`NUM_JOBS`](http://doc.crates.io/environment-variables.html#environment-variables-cargo-sets-for-build-scripts), however, to limit parallelism and I'd personally like to keep the dependencies of gcc-rs pretty lean (rayon pulls in rand/num_cpus/libc as well).

I think I'll probably just do this via a small "custom thread pool" which is a little bit more code but shouldn't be too bad! I'll post a commit in a few minutes.

**Comment by alexcrichton** [comment]
Bah nevermind, too complicated, crates are easy!

**Comment by nikomatsakis** [comment]
@alexcrichton note that Rayon does allow you to configure the number of helper threads

**Comment by nikomatsakis** [comment]
I think you can either set it globally, or make a special pool of a fixed size and install it using TLS, I forget exactly :)

**Comment by alexcrichton** [comment]
Ok hm I'm having second thoughts now, so I've moved rayon to a Cargo feature called `parallel` which is off by default for now (in the theory that most C code is actually very small). This can be enabled though via:

```toml
[build-dependencies]
gcc = { version = "0.3", features = ["parallel"] }
```

**Comment by nipunn1313** [comment]
Yep makes sense! I also had some qualms about adding a dependency to a build step, but feature gating seems like a good tradeoff for now. Thanks!

**Pull request merged**
