### PR TITLE
Support CROSS_COMPILE environment variable

### PR DESCRIPTION
**Pull request by jdub**
Used as last resort when HOST != TARGET.

### CODE REVIEW

**Comment by jdub** [comment]
Intended as one approach to alexcrichton/gcc-rs#82.

This is kinda ugly, because I had to juggle an `Option<String>` into an `Option<&str>` and didn't want to muck around too much with the logic in the `host != target` if block.

No tests or docs because I'm spitballing an approach for now. 😳

**Comment by alexcrichton** [comment]
Thanks! I wonder if perhaps this should be prioritized over the fallback prefixes though? It seems like it this variable is set it's higher priority

**Comment by jdub** [comment]
Hmm, yeah. 😳

This is a bit ooky, but it looks better than `if cross_compile.is_some() { … } else { match … }`.

**Comment by alexcrichton** [comment]
Thanks!

**Comment by jdub** [comment]
Oh! That is a surprise. I hadn't written docs, tests, or extended it to the other tools yet. I'll follow up in a separate PR. 😀

**Comment by alexcrichton** [comment]
Oh ok seems fine to me :)

**Pull request merged**
