### PR TITLE
rename "netbsdelf" Rust triples to "netbsd"

### PR DESCRIPTION
**Pull request by jakllsch**
Needed for recently-upstreamed i686-unknown-netbsd Rust target.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like a few stray merge commits showed up?

**Comment by jakllsch** [comment]
Yeah, looks like a good number of them did.  Should I do a new pull request from a rebased branch?

**Comment by alexcrichton** [comment]
Nah you should be able to just force-push to this branch

**Comment by lucab** [comment]
Bump. Commit history looks clean now, anything else missing?

**Comment by alexcrichton** [comment]
Looks great!

**Comment by alexcrichton** [comment]
@jakllsch sorry for the delay, feel free to ping whenever a PR is updated, unfortunately GitHub doesn't send out emails for that :(

**Pull request merged**
