### PR TITLE
Add some panic conditions

### PR DESCRIPTION
**Pull request by rap2hpoutre**
Just a try in order to help on https://github.com/alexcrichton/gcc-rs/issues/181. I don't know gcc and I'm not english, so the quality of this PR may be a bit poor!

I found another `unwrap` in a public function (`expand`) so I added a doc for this one too. I'm not sure about the text "compiler path has an invalid file name" though.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could you also mention that panics can originate if the compiler can't be found or otherwise fails?

**Comment by rap2hpoutre** [comment]
Thanks! So you mean replacing: 

 > Panics if compiler path has an invalid file name.

By:

> Panics if compiler path has an invalid file name, if it can not be found or otherwise fails

Am I right?

**Comment by rap2hpoutre** [comment]
(build failed but I don't think it's related to my commit)

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
