### PR TITLE
Perform debug builds under debug profile

### PR DESCRIPTION
**Pull request by jdub**

### CODE REVIEW

**Comment by jdub** [comment]
Is this appropriate for the `ios` target? I'm assuming it would use `clang`, and `-g` is compatible and desirable.

**Comment by alexcrichton** [comment]
Oh wow, this is like the one thing you expect gcc-rs to do and I forgot to do it, thanks!

I think `/DEBUG` on MSVC is just a flag to the linker, not the compiler itself, but I think `/Z7` should do the trick.

Also yeah calling gcc or clang with `-g` should be fine.

**Comment by jdub** [comment]
D'oh! Fixed.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
