### PR TITLE
Config: accept Into<Option<&str>> instead of Option<&str>

### LINKED ISSUE #224: Accept Into<Option<&str>> rather than Option<&str> in Config methods
There are currently three Config methods that take Option\<&str\>. It seems like they are commonly going to be called with Some string.

```rust
define("FOO", Some("BAR"))
```

Into\<Option\<&str\>\> could make the calls look neater.

```rust
define("FOO", "BAR")
define("FOO", None) // uncommon
```

### PR DESCRIPTION
**Pull request by laumann**
Per @dtolnay's suggestion, change methods on Config that accepts Option<&str> to
accept Into<Option<&str>> to make the calls look neater.

Fixes #224

### CODE REVIEW

**Comment by laumann** [comment]
I don't know what happened with AppVeyor :confused:

**Comment by opilar** [comment]
@laumann maybe we can close and reopen the issue to restart AppVeyor?

**Comment by laumann** [comment]
@opilar Thanks for the tip :-) Seems to be running now

**Comment by alexcrichton** [comment]
Thanks @laumann!

**Comment by laumann** [comment]
Happy to be of help :smile:

**Pull request merged**
